# security:
#     encoders:
#         App\Entity\User:
#             algorithm: auto
#         Symfony\Component\Security\Core\User\User:
#             algorithm: bcrypt

#     providers:
#         entity_provider:
#             entity:
#                 class: App\Entity\User
#                 property: mail
                
#         in_memory:
#             memory:
#                 users:
#                     admin:
#                         password: $2y$13$qD8Zp5bQJG6M2AiZJtVqhuyucYI7ip1B2taT..LU/.qG9NwOhNvx6
#                         roles: 'ROLE_ADMIN'
        

#     firewalls:
#         dev:
#             pattern: ^/(_(profiler|wdt)|css|images|js)/
#             security: false
        
#         api:
#             pattern:  ^/api
#             provider: entity_provider
#             stateless: true
#             anonymous: true
#             json_login:
#                 username_path: mail
#                 check_path: /api/login_check
#                 success_handler: lexik_jwt_authentication.handler.authentication_success
#                 failure_handler: lexik_jwt_authentication.handler.authentication_failure
#             guard:
#                 authenticators:
#                     - lexik_jwt_authentication.jwt_token_authenticator
#             # logout:
#             #     path: app_logout
#             #     where to redirect after logout
#             #     target: app_any_route

        
#         main:
#             pattern: ^/
#             provider: entity_provider
#             stateless: true
#             logout: true
#             anonymous: ~
#             form_login: 
#                 login_path: login
#                 check_path: login
            
#                 success_handler: lexik_jwt_authentication.handler.authentication_success
#                 failure_handler: lexik_jwt_authentication.handler.authentication_failure
#             guard:
#                 authenticators:
#                     - lexik_jwt_authentication.jwt_token_authenticator
                
            
       
        
#     access_control:
        
        
#         - { path: ^/admin, role: ROLE_ADMIN }
#         - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#         - { path: ^/, role : IS_AUTHENTICATED_ANONYMOUSLY }
#         - { path: ^/api/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        
#         - { path: ^/api$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#         - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

#     role_hierarchy:
#        ROLE_ADMIN: 'ROLE_ADMIN'

security:
    encoders:
        App\Entity\User:
            algorithm: auto
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt

    providers:
        entity_provider:
            entity:
                class: App\Entity\User
                property: mail
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$qD8Zp5bQJG6M2AiZJtVqhuyucYI7ip1B2taT..LU/.qG9NwOhNvx6
                        roles: 'ROLE_ADMIN'
        

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        api:
            pattern:  ^/api
            provider: entity_provider
            stateless: true
            anonymous: true
            json_login:
                username_path: mail
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
            # logout:
            #     path: app_logout
            #     where to redirect after logout
            #     target: app_any_route

        
        main:
            pattern: ^/
            provider: entity_provider
            form_login: 
                login_path: login
                check_path: login
                use_referer: true
                
            logout: true
            anonymous: ~
       
        
    access_control:
        
        
        - { path: ^/admin, role: ROLE_ADMIN}
        - { path: ^/dashboard, role: ROLE_USER}
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role : IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        
        - { path: ^/api$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

    role_hierarchy:
       ROLE_ADMIN: 'ROLE_USER'
       ROLE_USER: 'ROLE_USER'

    